export const RANGE_SLIDER_MIN_VALUE = 500000;
export const RANGE_SLIDER_MAX_VALUE = 60000000;

export const RANGE_SLIDER_EMPLOYEE_MIN_VALUE = 100;
export const RANGE_SLIDER_EMPLOYEE_MAX_VALUE = 1000000;

// Titles
export const VOLUME_IN_PRICE = "VOLUME*PRICE";
export const VOLUME = "VOLUME";
export const MARKET_CAPITALIZATION = "MARKET CAPITALIZATION";
export const NUMBER_OF_EMPLOYEES = "NUMBER OF EMPLOYEES";
export const CHANGE = "CHANGE";
export const CHANGE_PERCENT = "CHANGE %";
export const PRICE_TO_EARNING_RATIO = "PRICE TO EARNINGS RATIO (TTM)";
export const SECTOR = "SECTOR";
export const TECHNICAL_RATING = "TECHNICAL RATING";
export const PRICE = "PRICE"