export const RANGE_SLIDER_MIN_VALUE = 50;
export const RANGE_SLIDER_MAX_VALUE = 300000000;

export const VOLUME_RANGE_SLIDER_MIN_VALUE = 1000;
export const VOLUME_RANGE_SLIDER_MAX_VALUE = 300000000;

export const MARKET_KAP_RANGE_SLIDER_MIN_VALUE = 400000000000;
export const MARKET_KAP_RANGE_SLIDER_MAX_VALUE = 3000000000000;

export const EMPLOYEE_RANGE_SLIDER_MIN_VALUE = 100;
export const EMPLOYEE_RANGE_SLIDER_MAX_VALUE = 5000000;

export const PRICE_IN_VOLUME_RANGE_SLIDER_MIN_VALUE = 1000000000;
export const PRICE_IN_VOLUME_SLIDER_MAX_VALUE = 50000000000;

export const RANGE_SLIDER_STEP_VALUE = 1000000;

export const RANGE_SLIDER_EMPLOYEE_MIN_VALUE = 100;
export const RANGE_SLIDER_EMPLOYEE_MAX_VALUE = 1000000;

// Titles
export const VOLUME_IN_PRICE = "VOLUME*PRICE";
export const VOLUME = "VOLUME";
export const MARKET_CAPITALIZATION = "MARKET CAPITALIZATION";
export const NUMBER_OF_EMPLOYEES = "NUMBER OF EMPLOYEES";
export const CHANGE = "CHANGE";
export const CHANGE_PERCENT = "CHANGE %";
export const PRICE_TO_EARNING_RATIO = "PRICE TO EARNINGS RATIO (TTM)";
export const SECTOR = "SECTOR";
export const TECHNICAL_RATING = "TECHNICAL RATING";
export const PRICE = "PRICE";
export const EMPLOYEE = "EMPLOYEES";
